from celex_by_task import (SEEDS, RESULTSDIR, DATASET_PATH, DATASET_FOLDS,
    DATASET_TRAINFILE_NAME, DATASET_DEVFILE_NAME, DATASET_TESTFILE_NAME,
    MODEL_CONFIGS, ALIGN_CONFIGS, MODE_CONFIGS, MORE_PARAMS)

RESULTSDIR += 'celex2PIE'

DATASET_SHORTNAME = 'celex2PIE'
# The concatenation of DATASET_PATH/DATASET_FOLD/DATASET_TRAINFILE_NAME gives the filepath
DATASET_PATH += '2PIE-13PKE/0500/'